@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "AddressBook Storage" #F4F6F6{
Class "<<interface>>\nAddressBookStorage" as AddressBookStorage
Class JsonAddressBookStorage
Class JsonSerializableAddressBook
Class JsonAdaptedPerson
Class JsonAdaptedTag
}

package "ScheduleBoard Storage" #F4F6F6{
Class "<<interface>>\nScheduleBoardStorage" as ScheduleBoardStorage
Class JsonScheduleBoardStorage
Class JsonSerializableScheduleBoard
Class JsonAdaptedSchedule
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -down-> "1" UserPrefsStorage
StorageManager -down-> "1" AddressBookStorage
StorageManager -down-> "1" ScheduleBoardStorage

Storage --|> UserPrefsStorage
Storage --|> AddressBookStorage
Storage --|> ScheduleBoardStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonAddressBookStorage .up.|> AddressBookStorage
JsonAddressBookStorage ..> JsonSerializableAddressBook
JsonSerializableAddressBook --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedTag

JsonScheduleBoardStorage .up.|> ScheduleBoardStorage
JsonScheduleBoardStorage ..> JsonSerializableScheduleBoard
JsonSerializableScheduleBoard --> "*" JsonAdaptedSchedule


@enduml
